### ISSUE TITLE
Pontem Wallet Adapter Not Working Correctly

### ISSUE THREAD

**Issue by Pasha8914** [aptos-labs/aptos-wallet-adapter#495]
# Pontem Wallet Adapter Not Working Correctly in @aptos-labs/wallet-adapter-react  

## **Description**  
I encountered an issue where `@aptos-labs/wallet-adapter-react` does not work correctly with the **Pontem** wallet.  

## **Steps to Reproduce**  
1. Use `useWallet().account` to retrieve the public key.  
2. Attempt to sign a transaction using `signTransaction`.  

## **Expected Behavior**  
- `useWallet().account.publicKey` should return a **PublicKey instance** instead of a string (as implemented in other wallets like Petra).  
- `signTransaction` should return a **valid authenticator** (according to the types).  

## **Actual Behavior**  
- `useWallet().account.publicKey` returns a **string** instead of a **PublicKey class**.  
- `signTransaction` returns an object where `authenticator` is **undefined**.  

#### **Issue with PublicKey**
```typescript
const { account } = useWallet();
console.log(typeof account.publicKey); // string (Expected: PublicKey) 
```

#### **Issue with signTransaction**
```typescript
const signedTransaction = await signTransaction({ transactionOrPayload: rawTransaction });
console.log(signedTransaction.authenticator); // undefined
```

    "@aptos-labs/ts-sdk": "^1.35.0",
    "@aptos-labs/wallet-adapter-ant-design": "^4.0.3",
    "@aptos-labs/wallet-adapter-react": "^4.1.0",
    "@aptos-labs/wallet-standard": "^0.3.0",
    "aptos": "^1.21.0",

**Comment by 0xPoint** [comment]
@gsong @kaw2k @turshija @scottphc 
🤝 Hey team, I need your magic!
This issue is patiently waiting for a solution, and I’m counting on your wisdom! Any thoughts on how we can tackle it? 🛠️

Let me know if you want any tweaks! 😊

**Comment by Pasha8914** [comment]
@gsong @kaw2k @turshija @scottphc 
🤝 Hey team, I need your magic!
This issue is patiently waiting for a solution, and I’m counting on your wisdom! Any thoughts on how we can tackle it? 🛠️

Let me know if you want any tweaks! 😊

**Comment by 0xmaayan** [comment]
Thanks for reporting! Will let the Pontem wallet team know about it!

**Comment by 0xmaayan** [comment]
The issue has been resolved

**Comment by phatln** [comment]
With version 7.2.2, we're still facing this issue. Any thoughts?

**Comment by 0xmaayan** [comment]
Thanks @phatln , we let the Pontem team know
